return {
    Dark = {
        Name = "Dark",
        Accent = "#181818",
        Outline = "#FFFFFF",
        Text = "#FFFFFF",
        PlaceholderText = "#999999",
    },
    Light = {
        Name = "Light",
        Accent = "#FFFFFF",
        Outline = "#000000",
        Text = "#000000",
        PlaceholderText = "#777777",
    },
    Rose = {
        Name = "Rose",
        Accent = "#500830",
        Outline = "#FFFFFF",
        Text = "#FFFFFF",
        PlaceholderText = "#6B7280",
    },
    -- Lime = {
    --     Name = "Lime",
    --     Accent = "#A7F3D0",
    --     Outline = "#1D4ED8",
    --     Text = "#1D4ED8",
    --     PlaceholderText = "#4B5563",
    -- },
    -- Emerald = {
    --     Name = "Emerald",
    --     Accent = "#093502",
    --     Outline = "#034309",
    --     Text = "#FFFFFFFF",
    --     PlaceholderText = "#6B7280",
    -- },
    -- Sky = {
    --     Name = "Sky",
    --     Accent = "#065e82",
    --     Outline = "#033f43",
    --     Text = "#FFFFFF",
    --     PlaceholderText = "#6B7280",
    -- },
    -- Amber = {
    --     Name = "Amber",
    --     Accent = "#F59E0B",
    --     Outline = "#F97316",
    --     Text = "#7C2D12",
    --     PlaceholderText = "#9CA3AF",
    -- },
}